<?php

/**
 * @file
 * Replace missing images module.
 *
 * Todo:
 * - Replace all images or only missing images?
 */

/**
 * Implements hook_preprocess_HOOK().
 *
 * @param array $variables
 *   The image variables.
 */
function replace_missing_images_preprocess_image(&$variables) {

  // Check the image uri.
  if (!empty($variables['uri'])) {

    // Create the full file url.
    $url = file_create_url($variables['uri']);

    if (!file_exists($url)) {
      _replace_missing_images_replace_image($variables);
    }
  }
}

/**
 * Actually replace the image.
 *
 * @param array $variables
 *   The image variables.
 */
function _replace_missing_images_replace_image(array &$variables) {

  // Get the replace_missing_images config.
  $config = \Drupal::config('replace_missing_images.settings');

  // Check if enabled.
  if (!empty($config->get('enabled'))) {

    // Check which placeholder service to use.
    $placeholder_service = $config->get('predefined_placeholder_service');
    if (empty($placeholder_service)) {
      $custom = $config->get('use_custom_placeholder_service');
      if (!empty($custom)) {
        $placeholder_service = $config->get('custom_placeholder_service');
      }
    }

    // Get the default image width and height.
    $width = $config->get('default_placeholder_image_width');
    $height = $config->get('default_placeholder_image_height');

    // Check for specified image width and height.
    if (!empty($variables['width'])) {
      $width = $variables['width'];
    }
    if (!empty($variables['height'])) {
      $height = $variables['height'];
    }

    // Replace the width and height placeholders.
    $placeholder_url = str_replace(['[width]','[height]'], [$width, $height], $placeholder_service);

    // Check for the unique setting and add a random hash to the url.
    if ($config->get('unique')) {
      $placeholder_url .= '?unique=' . _replace_missing_images_get_random_string();
    }

    // Replace the image.
    $variables['uri'] = $placeholder_url;
    $variables['attributes']['src'] = $placeholder_url;
  }
}

/**
 * Generate a random string with letters.
 *
 * @param int $length
 *   The amount of letters.
 *
 * @return string
 *   Returns a random string.
 */
function _replace_missing_images_get_random_string(int $length = 5) {
  $characters = '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ';
  $random_string = '';
  for ($i = 0; $i < $length; $i++) {
    $index = rand(0, strlen($characters) - 1);
    $random_string .= $characters[$index];
  }
  return $random_string;
}
